config/routes.rb
BaconTimer::Application.routes.draw do
  # root :to => "timers#index"
  root :to => "timers#welcome"
  resources :timers, :except => [:edit, :update, :destroy, :show]
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :destination, :type

  VALID_TYPES = %w( 
    SmsNotification
    TwitterNotification
  )
  #  EmailNotification
  
  
  MESSAGE = "Your bacon is ready!"

  validates_presence_of :destination, :type
  validates_uniqueness_of :type, :scope => :timer_id
  validates_inclusion_of :type, :in => VALID_TYPES
  belongs_to :timer

  after_create :deliver

  def self.label
    # Defined in subclasses
  end

  def self.placeholder
    # Defined in subclasses
  end

end

app/models/sms_notification.rb
class SmsNotification < Notification

  validates_format_of :destination, :with => /^(\(\d{3}\)|\d{3})-?\d{3}-?\d{4}$/

  def destination=(destination)
    self[:destination] = destination.gsub(/\D/, '')
  end
  
  def self.label
    "Phone Number for SMS Notification"
  end

  def self.placeholder
    "3175551234"
  end

  def deliver
    Rails.logger.debug "... Sending SMS to #{destination}"
    TwilioAccount.sms.messages.create({
      :from => '+13175504935',
      :to   => destination,
      :body => MESSAGE})
  end
  handle_asynchronously :deliver,
    :run_at => Proc.new { |notification| notification.timer.duration.seconds.from_now }
end

app/models/timer.rb
class Timer < ActiveRecord::Base
  TEMPERATURE = "350"

  MAX_DURATION = 30.minutes
  MIN_DURATION = 15.minutes
  REMAINING_TIME_FUNCTION = "(created_at + (duration * interval '1 second'))"

  validates_numericality_of :duration, :greater_than => 0, :less_than_or_equal_to => MAX_DURATION
  validates_presence_of :name, :description, :duration

  scope :active, where("#{REMAINING_TIME_FUNCTION} > ?", Time.now)
  scope :remaining_ascending, order("#{REMAINING_TIME_FUNCTION} ASC")

  has_many :notifications, :dependent => :destroy
  accepts_nested_attributes_for :notifications,
    :reject_if => proc { |attributes| attributes['destination'].blank? }

  has_one :sms_notification
  accepts_nested_attributes_for :sms_notification,
    :reject_if => proc { |attributes| attributes['destination'].blank? }

  has_one :twitter_notification
  accepts_nested_attributes_for :twitter_notification,
    :reject_if => proc { |attributes| attributes['destination'].blank? }

  attr_accessible :duration, :name, :description, :sms_notification_attributes, :twitter_notification_attributes

  def self.default_duration
    MIN_DURATION + ((MAX_DURATION - MIN_DURATION) / 2.to_f)
  end

  def remaining_duration
    remaining = (duration - (Time.now - created_at)).to_i
    remaining >= 0 ? remaining : 0
  end
end

app/models/twitter_notification.rb
class TwitterNotification < Notification

  validates_format_of :destination, :with => /^[a-zA-Z0-9_]{1,20}$/i

  def self.label
    "Twitter Handle to Receive Alert"
  end

  def self.placeholder
    "YourTwitterName"
  end

  def deliver
    Rails.logger.debug "... Sending Tweet to #{destination}"
    Twitter.update("@#{destination} #{MESSAGE} #BACON #BaaS")
  end
  handle_asynchronously :deliver,
    :run_at => Proc.new { |notification| notification.timer.duration.seconds.from_now }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_analytics_token

  private

  def set_analytics_token
    @analytics_token ||= YAML.load_file("#{::Rails.root.to_s}/config/google_analytics.yml")[:token]
  end

end

app/controllers/timers_controller.rb
class TimersController < ApplicationController

  def index
    @timers = Timer.active.remaining_ascending

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timers }
    end
  end

  def new
    @timer = Timer.new
    Notification::VALID_TYPES.each do |type|
      @timer.send(:"build_#{type.underscore}")
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timer }
    end
  end

  def create
    @timer = Timer.new(params[:timer])

    respond_to do |format|
      if @timer.save
        format.html { redirect_to timers_path, notice: 'Timer was successfully created.' }
        format.json { render json: @timer, status: :created, location: @timer }
      else
        format.html { render action: "new" }
        format.json { render json: @timer.errors, status: :unprocessable_entity }
      end
    end
  end

  def welcome
    render action: "welcome"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def google_analytics
    "<script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '#{@analytics_token}', 'auto');
      ga('send', 'pageview');

    </script>".html_safe
  end

end

app/helpers/timers_helper.rb
module TimersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OinkTimer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag "application" %>
<%= yield :script %>
<%= google_analytics %>
</body>
</html>

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }

  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  -# Set the viewport width to device width for mobile
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

  %title= content_for?(:title) ? yield(:title) : "Untitled"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag

%body

  = yield

  = javascript_include_tag "application"

app/views/timers/index.html.haml
.full-white
  .left{:style => "float:left;text-align:left"}
    %h2 Current Bacon Orders
  .right{:style => "float:right;text-align:right"}
    = link_to "Create a new timer", new_timer_path, :class => "button large round success"
  .clear{:style => "float:clear"}
  %hr


  %ul.small-block-grid-4
    - @timers.each do |timer|
      %li.timer-block
        %h4= timer.name
        %h5
          - if timer.description.length > 40
            = "#{timer.description[0..40]}..."
          - else
            = timer.description
        %input{:value => "#{timer.remaining_duration}", :class => 'knob-timer'}
        %br
        %span
          - if timer.sms_notification.present?
            [SMS]
          - if timer.twitter_notification.present?
            [Tweet]

- content_for :script do
  :javascript
    $(document).ready(function(){
      $('.knob-timer').knob({
        readOnly : true,
        max      : #{Timer::MAX_DURATION}
      });

      setInterval(function(){
        $('.knob-timer').each(function(){
          var original = $(this).val();

          if(original > 0){
            $(this).val(original - 1).trigger('change');
          } else {
            $(this).parents('li:first').fadeOut('slow', function(){
              $(this).remove();
            });
          }
        });
      }, 1000);

    });
  

app/views/timers/new.html.haml
.row
  .columns.small-12
    %h4 Create your Oink Timer!
    %hr
    %h5 Please complete the following fields to create your order:
    = simple_form_for @timer do |f|
      = f.input :name, :label => "Your Name"
      = f.input :description, :label => "A brief description of what we're wrapping in bacon (this helps keep your orders organized!)"

      .panel{:style => "padding-bottom:2.5em"}
        = f.label "How would you like your bacon prepared?"
        .duration-slider
        = f.input :duration, :as => :hidden, :input_html => {:value => Timer.default_duration}

        .container
          .left{:style => "float:left;text-align:left"} Chewy
          .right{:style => "float:right;text-align:right"} Crispy
          .clear{:style => "float:clear"}
      
      %div.clearfix
        %p
        %h5 Choose a(n optional) method of notification:
        If you'd like to hang out near the break room, you're more than welcome to do that, and we'll holler at you when your bacon is ready!  If time allows, we might even have a robot deliver your order TO you!
        %p
        If you'd like to receive an automated alert when your bacon is ready, simply fill out one of the options below with the relevant information.
        %p
        - Notification::VALID_TYPES.each do |type|
          = f.simple_fields_for :"#{type.underscore}" do |notification_form|
            = notification_form.input :destination, :required => false, :label => type.constantize.label, :placeholder => type.constantize.placeholder
      %p
      = f.button :submit, "Submit Order!", :class => "large round success"

- content_for :script do
  :javascript
    $(document).ready(function(){
      $('.duration-slider').slider({
        max    : #{Timer::MAX_DURATION},
        min    : #{Timer::MIN_DURATION},
        value  : $('#timer_duration').val(),
        change : function(event, ui){
          $('#timer_duration').val(ui.value);
        }
      });
    });

app/views/timers/welcome.html.haml
.row
  .columns.small-12{:style => "text-align:center"}
    = image_tag "oinktimer.jpg", :width => 300
    %h2 Welcome to OinkTimer!
    %p The only web application that helps you make bacon (...that we're aware of)
  %p
    %strong Follow the instructions below to get started:
    %ul.disc
      %li Select an item* you want bacon-wrapped, or just decide how much regular bacon you want
      %li Scan our QR Code with your smart phone or visit www.baconbaconbaconbacon.com
      %li Enter your name, describe your bacon-order & use the slider to set how chewy/crispy you want it
      %li Fill in the Destination fields for your preferred method(s) of contact, and submit!

  %p{:style => "text-align:justify"}
    = "That's it!  When we receive your item-to-be-wrapped, we'll wrap it and bake it as oven-space becomes available.  Your items will be baked at #{Timer::TEMPERATURE} degrees for between #{Timer::MIN_DURATION/60} to #{Timer::MAX_DURATION/60} minutes, depending on where you set the crispiness slider.  You should receive your notice(s) about the same time your order completes baking.  Stop by the kitchen with a plate or bowl, ready to collect your delicious bacon!"

  %p
    %em * Precooked, edible items only, please.

  %p
    %strong= link_to "Create a Bacon Order!", new_timer_path, :class => "large round button success"